import { NextResponse } from 'next/server'
import { Stock } from '@/types'

// Mock stock data - In production, replace with real API calls
const generateMockStocks = (): Stock[] => {
  const stocks: Stock[] = [
    {
      symbol: 'AAPL',
      name: 'Apple Inc.',
      price: 178.50,
      change: 2.30,
      changePercent: 1.31,
      volume: 52345678,
      marketCap: 2.8e12,
      sector: 'Technology',
      peRatio: 28.5,
      dividendYield: 0.52,
    },
    {
      symbol: 'MSFT',
      name: 'Microsoft Corporation',
      price: 378.85,
      change: -1.20,
      changePercent: -0.32,
      volume: 23456789,
      marketCap: 2.8e12,
      sector: 'Technology',
      peRatio: 32.1,
      dividendYield: 0.75,
    },
    {
      symbol: 'GOOGL',
      name: 'Alphabet Inc.',
      price: 142.30,
      change: 3.45,
      changePercent: 2.48,
      volume: 34567890,
      marketCap: 1.8e12,
      sector: 'Communication Services',
      peRatio: 24.8,
      dividendYield: 0,
    },
    {
      symbol: 'AMZN',
      name: 'Amazon.com Inc.',
      price: 151.20,
      change: 1.80,
      changePercent: 1.20,
      volume: 45678901,
      marketCap: 1.6e12,
      sector: 'Consumer Cyclical',
      peRatio: 45.2,
      dividendYield: 0,
    },
    {
      symbol: 'TSLA',
      name: 'Tesla, Inc.',
      price: 248.90,
      change: -5.60,
      changePercent: -2.20,
      volume: 78901234,
      marketCap: 7.9e11,
      sector: 'Consumer Cyclical',
      peRatio: 65.3,
      dividendYield: 0,
    },
    {
      symbol: 'META',
      name: 'Meta Platforms Inc.',
      price: 485.60,
      change: 8.90,
      changePercent: 1.87,
      volume: 12345678,
      marketCap: 1.2e12,
      sector: 'Communication Services',
      peRatio: 22.4,
      dividendYield: 0,
    },
    {
      symbol: 'NVDA',
      name: 'NVIDIA Corporation',
      price: 495.20,
      change: 15.80,
      changePercent: 3.29,
      volume: 67890123,
      marketCap: 1.2e12,
      sector: 'Technology',
      peRatio: 58.7,
      dividendYield: 0.03,
    },
    {
      symbol: 'JPM',
      name: 'JPMorgan Chase & Co.',
      price: 156.80,
      change: 0.90,
      changePercent: 0.58,
      volume: 12345678,
      marketCap: 4.5e11,
      sector: 'Financial Services',
      peRatio: 11.2,
      dividendYield: 2.45,
    },
    {
      symbol: 'V',
      name: 'Visa Inc.',
      price: 265.40,
      change: 2.10,
      changePercent: 0.80,
      volume: 9876543,
      marketCap: 5.4e11,
      sector: 'Financial Services',
      peRatio: 28.9,
      dividendYield: 0.75,
    },
    {
      symbol: 'JNJ',
      name: 'Johnson & Johnson',
      price: 158.20,
      change: -0.60,
      changePercent: -0.38,
      volume: 8765432,
      marketCap: 4.1e11,
      sector: 'Healthcare',
      peRatio: 24.6,
      dividendYield: 3.05,
    },
    {
      symbol: 'WMT',
      name: 'Walmart Inc.',
      price: 165.30,
      change: 1.20,
      changePercent: 0.73,
      volume: 7654321,
      marketCap: 4.4e11,
      sector: 'Consumer Defensive',
      peRatio: 26.8,
      dividendYield: 1.52,
    },
    {
      symbol: 'PG',
      name: 'Procter & Gamble Co.',
      price: 152.60,
      change: 0.40,
      changePercent: 0.26,
      volume: 6543210,
      marketCap: 3.6e11,
      sector: 'Consumer Defensive',
      peRatio: 24.3,
      dividendYield: 2.48,
    },
    {
      symbol: 'MA',
      name: 'Mastercard Inc.',
      price: 425.80,
      change: 3.20,
      changePercent: 0.76,
      volume: 5432109,
      marketCap: 4.1e11,
      sector: 'Financial Services',
      peRatio: 35.2,
      dividendYield: 0.58,
    },
    {
      symbol: 'DIS',
      name: 'The Walt Disney Company',
      price: 95.40,
      change: -1.30,
      changePercent: -1.34,
      volume: 12345678,
      marketCap: 1.7e11,
      sector: 'Communication Services',
      peRatio: 18.9,
      dividendYield: 0.25,
    },
    {
      symbol: 'NFLX',
      name: 'Netflix, Inc.',
      price: 485.20,
      change: 12.50,
      changePercent: 2.64,
      volume: 9876543,
      marketCap: 2.1e11,
      sector: 'Communication Services',
      peRatio: 42.3,
      dividendYield: 0,
    },
    {
      symbol: 'AMD',
      name: 'Advanced Micro Devices',
      price: 128.50,
      change: 2.80,
      changePercent: 2.23,
      volume: 8765432,
      marketCap: 2.1e11,
      sector: 'Technology',
      peRatio: 38.5,
      dividendYield: 0,
    },
    {
      symbol: 'INTC',
      name: 'Intel Corporation',
      price: 45.20,
      change: -0.80,
      changePercent: -1.74,
      volume: 23456789,
      marketCap: 1.9e11,
      sector: 'Technology',
      peRatio: 28.4,
      dividendYield: 1.33,
    },
    {
      symbol: 'CSCO',
      name: 'Cisco Systems, Inc.',
      price: 52.80,
      change: 0.30,
      changePercent: 0.57,
      volume: 12345678,
      marketCap: 2.1e11,
      sector: 'Technology',
      peRatio: 15.2,
      dividendYield: 3.18,
    },
    {
      symbol: 'PFE',
      name: 'Pfizer Inc.',
      price: 42.60,
      change: -0.50,
      changePercent: -1.16,
      volume: 34567890,
      marketCap: 2.4e11,
      sector: 'Healthcare',
      peRatio: 14.8,
      dividendYield: 4.21,
    },
    {
      symbol: 'BAC',
      name: 'Bank of America Corp.',
      price: 35.20,
      change: 0.40,
      changePercent: 1.15,
      volume: 45678901,
      marketCap: 2.8e11,
      sector: 'Financial Services',
      peRatio: 10.8,
      dividendYield: 2.84,
    },
  ]

  return stocks
}

export async function GET() {
  try {
    // In production, replace this with actual API calls
    // Example: const response = await fetch('https://api.example.com/stocks')
    const stocks = generateMockStocks()
    
    return NextResponse.json(stocks)
  } catch (error) {
    console.error('Error fetching stocks:', error)
    return NextResponse.json(
      { error: 'Failed to fetch stocks' },
      { status: 500 }
    )
  }
}

